name: Build & Push KFP omponent

on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to build"
        required: true
        default: ${{ github.ref }}
        type: string
      component-name:
        description: "Name of the component"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - run: |
          echo "python_version=$(cat components/${{ github.event.inputs.component_name }}/.python-version)" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kfp

      - name: Configure GCloud Credentials
        id: configure-gcloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/829992204381/locations/global/workloadIdentityPools/kflow-github-pool/providers/kflow-github-provider
          service_account: terraform@kflow-artifacts.iam.gserviceaccount.com

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.configure-gcloud.outputs.access_token }}

      - name: Docker Meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          context: git
          images: |
            us-central1-docker.pkg.dev/kflow-artifacts/kfp-components/${{ github.event.inputs.component_name }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch,prefix=branch/

      - name: Build Component Docker Image
        uses: docker/build-push-action@v4
        with:
          context: components/${{ github.event.inputs.component_name }}/src/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
