name: Build kfp-vectorize-dataset

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Component Image
    uses: ./.github/workflows/build-component.yml
    with:
      component-name: kfp-vectorize-dataset
      ref: ${{ github.ref }}
    permissions:
      contents: read
      id-token: write
